MusicBlog/Music/urls.py
from django.conf.urls import url
from . import views

app_name = 'Music'

urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),
    #/music/album_id/
    url(r'^(?P<album_id>[0-9]+)/$',views.details,name='details'),
    #/music/<album-d>/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite')
]

MusicBlog/MusicBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Music/', include('Music.urls')),
]

MusicBlog/Music/models.py
from django.db import models


# Create your models here.
# Some of the data for the models come from the data scrapper while other
# data has to be manually filled or collected running spider/crawler and retrieve information
# from other data sources
class Album(models.Model):
    album_name = models.CharField(max_length=250)
    album_artist = models.CharField(max_length=250)
    album_songscount= models.IntegerField(default=1)
    album_logo = models.CharField(max_length=1000)
    album_genre = models.CharField(max_length=250)

    def __str__(self):
        return self.album_name + '-'+ self.album_artist

class Songs(models.Model):
    #Assuming an album has various artists and songs are of various genre
    song_album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    song_artist = models.CharField(max_length=250)
    song_genre = models.CharField(max_length=250)
    song_length = models.TimeField()
    song_type = models.CharField(max_length=10)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + '-' + self.song_artist

MusicBlog/Music/views.py
from django.http import Http404
# serialize to Iterate over model column names and values in template
from django.shortcuts import get_object_or_404, render

from .models import Album, Songs


# Create your views here.
def index(request):
    #to iterate over all columns in the model
    Avail_albums =  Album.objects.all()
    meta_names = Album._meta.fields
    #to iterate over selected column names
    #Avail_albums = serializers.serialize( "python", Album.objects.all(),fields = ('album_title','album_artist))
    context = {
        'avail_albums' : Avail_albums,
        'columns_name' : meta_names
    }
    return render(request,'music/index.html',context)

#details of particular album when selected
def details(request,album_id):
    try:
        returned_album = Album.objects.get(pk=album_id)
        song_columns = Songs._meta.fields
        title = Songs._meta.get_field('song_title')
        artist =Songs._meta.get_field('song_artist')
        length = Songs._meta.get_field('song_length')
        stype = Songs._meta.get_field('song_type')
        indi_cols = [title,artist,length,stype]
        #serializers.serialize( "python", Songs.objects.all(),fields = ('song_title','song_artist','song_length'))
        context = {
        'album': returned_album,
        'song_columns':song_columns,
        'indi_cols':indi_cols
        }
    except Album.DoesNotExist:
        raise Http404("Album No longer exists")
    return render(request,'music/Details.html',context)

def favorite(request,album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.songs_set.get(pk = request.POST['song'])
    except (KeyError, Songs.DoesNotExist):
        return render(request,'music/Details.html',
                        {'album':album,
                        'error_message':"Please select a valid option (Song)"}
                        )
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/Details.html', {'album':album})

MusicBlog/Music/templates/music/Details.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <title>{{ album.album_name }}</title>
  <meta charset="UTF-8">
  <title>Music Albums</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</head>
<body>
  <img src="{{ album.album_logo }}" height="220px" width="220px">
  <h1>{{ album.album_name }}</h1>
  <h2>{{ album.album_artist }}</h2>
  {#{% if error_message %}#}
  {#<p><strong>Error exists</strong></p>#}
  {#{% endif %}#}

  <form action="{% url 'Music:favorite' album.id%}" method="post">
    {% csrf_token %}
    <div class="table-responsive">
      <table class="table">
        <thead class="thead-inverse"  style="width: 100vw;">
          <tr>
            {#list all the existing columns or required columsn in the model Album and display them in a table header#}
            {%  for column in indi_cols%}
            {% if column.name %}
            <th style="text-align : center;">{{ column.verbose_name }}</th>
            {% endif %}
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {# Loop through the existing records/Songs in Album  #}
          {% for song in album.songs_set.all %}
          <tr style="text-align: center">
            <td>
              <input style="float: left;" type="radio" id="song{{ forloop.counter }}" name="song" value={{ song.id }}/>
              {# <label for ="song{{ forloop.counter }}"> #} &nbsp;
                {{ song.song_title }}
                <td>{{ song.song_artist }}</td>
                <td>{{ song.song_length }}</td>
                <td>{{ song.song_type }}</td>
                <td>{{ song.song_genre }}
                {% if song.is_favorite %}
                <img style="float: right; vertical-align: middle" src="http://imgur.com/A6lqZvX.png" >
                {% endif %}</td>
              {#</label>#}<br>
            </td>
          </tr>
          {% endfor %}
          <button type="submit" class="btn btn-primary">Favorite</button>
        </tbody>
      </table>
    </div>
  </form>
</body>
</html>

MusicBlog/Music/templates/music/favorite.html
<h2>{{album.album_artist}}</h2>

MusicBlog/Music/templates/music/index.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music Albums</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" type= "text/css" href="{% static '/music/css/style.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</head>
<body>
<table class="table">
    <thead class="thead-inverse">
    <tr>
        {#list all the existing columns or required columsn in the model Album and display them in a table header#}
        {%  for column in columns_name%}
            <th>{{ column.verbose_name }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {# Loop through the existing records/Albums and generate a HTMl link for each album #}
    {% for album in avail_albums %}
        <tr>
            <td>{{ album.id }}</td>
            <td><a href="{% url 'Music:details' album.id %}">{{ album.album_name }} </a></td>
            <td>{{ album.album_artist }}</td>
            <td>{{ album.album_count }}</td>
            <td><img src="{{ album.album_logo }}"  height="42" width="42" ></td>
            <td>{{ album.album_genre }}</td>

        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>